version: "3"

vars:
  UID:
    sh: id -u
  GID:
    sh: id -g

env:
  UID: "{{.UID}}"
  GID: "{{.GID}}"

tasks:
  build:
    desc: Build the Docker Compose stack images
    cmds:
      - docker compose build

  up:
    desc: Start the Docker Compose stack
    cmds:
      - docker compose up

  down:
    desc: Stop the Docker Compose stack
    cmds:
      - docker compose down

  migrate:
    desc: Run Doctrine Migrations inside the API container
    cmds:
      - docker compose exec api bin/console doctrine:migrations:migrate --no-interaction

  import:
    desc: Run the city dataset import command inside the API container
    cmds:
      - docker compose exec api bin/console app:city:import
