version: "3"

vars:
  UID:
    sh: id -u
  GID:
    sh: id -g

env:
  UID: "{{.UID}}"
  GID: "{{.GID}}"

tasks:
  build:
    desc: Build the Docker Compose stack images
    cmds:
      - docker compose build

  up:
    desc: Start the Docker Compose stack
    cmds:
      - docker compose up

  down:
    desc: Stop the Docker Compose stack
    cmds:
      - docker compose down
